
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul 25 2025 15:01:16 IST (Jul 25 2025 09:31:16 UTC)

// Verification Directory fv/soc_top 

module soc_top(clk_fast, clk_slow, rst_n, pwr_dom1_on, pwr_dom2_on,
     out_dom1, out_dom2);
  input clk_fast, clk_slow, rst_n, pwr_dom1_on, pwr_dom2_on;
  output [7:0] out_dom1, out_dom2;
  wire clk_fast, clk_slow, rst_n, pwr_dom1_on, pwr_dom2_on;
  wire [7:0] out_dom1, out_dom2;
  wire [7:0] reg_dom1;
  wire UNCONNECTED, n_0, n_1, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_20, n_22, n_27, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, \reg_dom2[0]_142 , \reg_dom2[0]_150 ,
       \reg_dom2[1]_143 , \reg_dom2[2]_144 ;
  wire \reg_dom2[3]_145 , \reg_dom2[4]_146 , \reg_dom2[5]_147 ,
       \reg_dom2[6]_148 , \reg_dom2[7]_149 ;
  SDFFRHQX1 \reg_dom2_reg[7] (.RN (rst_n), .CK (clk_slow), .D (n_16),
       .SI (n_27), .SE (n_57), .Q (\reg_dom2[7]_149 ));
  DFFRHQX1 \reg_dom2_reg[6] (.RN (rst_n), .CK (clk_slow), .D (n_58), .Q
       (\reg_dom2[6]_148 ));
  OA21X1 g405__2398(.A0 (n_56), .A1 (n_55), .B0 (n_57), .Y (n_58));
  DFFRHQX1 \reg_dom2_reg[5] (.RN (rst_n), .CK (clk_slow), .D (n_54), .Q
       (\reg_dom2[5]_147 ));
  DFFRHQX1 \reg_dom1_reg[6] (.RN (rst_n), .CK (clk_fast), .D (n_53), .Q
       (reg_dom1[6]));
  SDFFRHQX1 \reg_dom1_reg[7] (.RN (rst_n), .CK (clk_fast), .D (n_1),
       .SI (reg_dom1[7]), .SE (n_52), .Q (reg_dom1[7]));
  NAND2XL g408__5107(.A (n_56), .B (n_55), .Y (n_57));
  AOI2BB1X1 g411__6260(.A0N (n_49), .A1N (n_50), .B0 (n_55), .Y (n_54));
  DFFRHQX1 \reg_dom2_reg[4] (.RN (rst_n), .CK (clk_slow), .D (n_51), .Q
       (\reg_dom2[4]_146 ));
  OA21X1 g403__4319(.A0 (reg_dom1[6]), .A1 (n_47), .B0 (n_52), .Y
       (n_53));
  DFFRHQX1 \reg_dom2_reg[3] (.RN (rst_n), .CK (clk_slow), .D (n_46), .Q
       (\reg_dom2[3]_145 ));
  AOI21XL g417__8428(.A0 (n_44), .A1 (n_45), .B0 (n_50), .Y (n_51));
  AND2X1 g414__5526(.A (n_49), .B (n_50), .Y (n_55));
  AOI21XL g409__6783(.A0 (n_43), .A1 (n_42), .B0 (n_47), .Y (n_48));
  NAND2XL g406__3680(.A (reg_dom1[6]), .B (n_47), .Y (n_52));
  DFFRHQX1 \reg_dom1_reg[4] (.RN (rst_n), .CK (clk_fast), .D (n_41), .Q
       (reg_dom1[4]));
  DFFRHQX1 \reg_dom2_reg[2] (.RN (rst_n), .CK (clk_slow), .D (n_40), .Q
       (\reg_dom2[2]_144 ));
  OA21X1 g423__1617(.A0 (n_38), .A1 (n_39), .B0 (n_45), .Y (n_46));
  NOR2XL g420__2802(.A (n_44), .B (n_45), .Y (n_50));
  NOR2XL g412__1705(.A (n_43), .B (n_42), .Y (n_47));
  OA21X1 g415__5122(.A0 (reg_dom1[4]), .A1 (n_36), .B0 (n_42), .Y
       (n_41));
  DFFRHQX1 \reg_dom2_reg[1] (.RN (rst_n), .CK (clk_slow), .D (n_35), .Q
       (\reg_dom2[1]_143 ));
  AOI21XL g429__8246(.A0 (n_33), .A1 (n_34), .B0 (n_39), .Y (n_40));
  NAND2XL g426__7098(.A (n_38), .B (n_39), .Y (n_45));
  DFFRHQX1 \reg_dom1_reg[2] (.RN (rst_n), .CK (clk_fast), .D (n_32), .Q
       (reg_dom1[2]));
  AOI21XL g421__6131(.A0 (n_30), .A1 (n_31), .B0 (n_36), .Y (n_37));
  NAND2XL g418__1881(.A (reg_dom1[4]), .B (n_36), .Y (n_42));
  OA21XL g435__5115(.A0 (n_22), .A1 (n_20), .B0 (n_34), .Y (n_35));
  NOR2XL g432__7482(.A (n_33), .B (n_34), .Y (n_39));
  DFFRHQX1 \reg_dom2_reg[0] (.RN (rst_n), .CK (clk_slow), .D (n_14), .Q
       (\reg_dom2[0]_142 ));
  OA21X1 g427__4733(.A0 (reg_dom1[2]), .A1 (n_17), .B0 (n_31), .Y
       (n_32));
  NOR2XL g424__6161(.A (n_30), .B (n_31), .Y (n_36));
  TBUFXL g36__9315(.A (n_56), .OE (pwr_dom2_on), .Y (out_dom2[6]));
  TBUFXL g35__9945(.A (n_27), .OE (pwr_dom2_on), .Y (out_dom2[7]));
  TBUFXL g38__2883(.A (n_13), .OE (pwr_dom2_on), .Y (out_dom2[4]));
  TBUFXL g39__2346(.A (n_38), .OE (pwr_dom2_on), .Y (out_dom2[3]));
  TBUFXL g6__1666(.A (n_15), .OE (pwr_dom2_on), .Y (out_dom2[2]));
  TBUFXL g40__7410(.A (n_22), .OE (pwr_dom2_on), .Y (out_dom2[1]));
  TBUFXL g41__6417(.A (n_20), .OE (pwr_dom2_on), .Y (out_dom2[0]));
  TBUFXL g37__5477(.A (n_49), .OE (pwr_dom2_on), .Y (out_dom2[5]));
  NAND2XL g438__2398(.A (n_20), .B (n_22), .Y (n_34));
  AOI21XL g433__5107(.A0 (n_12), .A1 (n_11), .B0 (n_17), .Y (n_18));
  INVXL g440(.A (n_27), .Y (n_16));
  CLKINVX1 g439(.A (n_15), .Y (n_33));
  INVXL g442(.A (n_20), .Y (n_14));
  CLKINVX1 g441(.A (n_13), .Y (n_44));
  DFFRHQX1 \reg_dom1_reg[0] (.RN (rst_n), .CK (clk_fast), .D (n_10), .Q
       (reg_dom1[0]));
  NAND2XL g430__6260(.A (reg_dom1[2]), .B (n_17), .Y (n_31));
  TBUFX1 g26__4319(.A (\reg_dom2[2]_144 ), .OE (\reg_dom2[0]_150 ), .Y
       (n_15));
  TBUFX1 g25__8428(.A (\reg_dom2[3]_145 ), .OE (\reg_dom2[0]_150 ), .Y
       (n_38));
  TBUFX1 g3__5526(.A (\reg_dom2[5]_147 ), .OE (\reg_dom2[0]_150 ), .Y
       (n_49));
  TBUFX1 g23__6783(.A (\reg_dom2[7]_149 ), .OE (\reg_dom2[0]_150 ), .Y
       (n_27));
  TBUFX1 g24__3680(.A (\reg_dom2[4]_146 ), .OE (\reg_dom2[0]_150 ), .Y
       (n_13));
  TBUFX1 g27__1617(.A (\reg_dom2[1]_143 ), .OE (\reg_dom2[0]_150 ), .Y
       (n_22));
  TBUFX1 g2__2802(.A (\reg_dom2[6]_148 ), .OE (\reg_dom2[0]_150 ), .Y
       (n_56));
  TBUFX1 g28__1705(.A (\reg_dom2[0]_142 ), .OE (\reg_dom2[0]_150 ), .Y
       (n_20));
  NOR2XL g436__5122(.A (n_12), .B (n_11), .Y (n_17));
  OA21XL g443__8246(.A0 (reg_dom1[0]), .A1 (pwr_dom1_on), .B0 (n_11),
       .Y (n_10));
  DFFRX1 \reg_dom2_reg[0]42 (.RN (rst_n), .CK (clk_slow), .D (n_0), .Q
       (UNCONNECTED), .QN (\reg_dom2[0]_150 ));
  TBUFXL g30__7098(.A (reg_dom1[6]), .OE (pwr_dom1_on), .Y
       (out_dom1[6]));
  TBUFXL g4__6131(.A (reg_dom1[4]), .OE (pwr_dom1_on), .Y
       (out_dom1[4]));
  TBUFXL g31__1881(.A (reg_dom1[5]), .OE (pwr_dom1_on), .Y
       (out_dom1[5]));
  TBUFXL g33__5115(.A (reg_dom1[1]), .OE (pwr_dom1_on), .Y
       (out_dom1[1]));
  TBUFXL g32__7482(.A (reg_dom1[2]), .OE (pwr_dom1_on), .Y
       (out_dom1[2]));
  TBUFXL g5__4733(.A (reg_dom1[3]), .OE (pwr_dom1_on), .Y
       (out_dom1[3]));
  TBUFXL g29__6161(.A (reg_dom1[7]), .OE (pwr_dom1_on), .Y
       (out_dom1[7]));
  TBUFXL g34__9315(.A (reg_dom1[0]), .OE (pwr_dom1_on), .Y
       (out_dom1[0]));
  NAND2XL g445__9945(.A (reg_dom1[0]), .B (pwr_dom1_on), .Y (n_11));
  INVXL g449(.A (reg_dom1[7]), .Y (n_1));
  INVXL g448(.A (pwr_dom2_on), .Y (n_0));
  DFFRX1 \reg_dom1_reg[3] (.RN (rst_n), .CK (clk_fast), .D (n_37), .Q
       (reg_dom1[3]), .QN (n_30));
  DFFRX1 \reg_dom1_reg[1] (.RN (rst_n), .CK (clk_fast), .D (n_18), .Q
       (reg_dom1[1]), .QN (n_12));
  DFFRX1 \reg_dom1_reg[5] (.RN (rst_n), .CK (clk_fast), .D (n_48), .Q
       (reg_dom1[5]), .QN (n_43));
endmodule

